### ISSUE TITLE
main batch without multiprocessing

### ISSUE THREAD

**Issue by michalsr** [cvlab-columbia/viper#23]
Whenever I turn off multiprocessing using main_batch, nothing runs. The models load and then that is it. I've tried debugging it but I haven't had any success.

**Comment by surisdi** [comment]
Hi, by "nothing run" do you mean that the program get stuck somewhere and never finishes, or it finishes without any output or error?

If it is the former, can you check that you are using an OpenAI model that is not `code-davinci-002`? That one was deprecated by OpenAI.

If it is the latter, can you use the new (latest commit) `utils.py` file? I removed the `HiddenPrints` utility so that it is easier to debug and see errors.

Does it work properly in the multiprocessing setting?

**Comment by michalsr** [comment]
Thanks for your quick response. The jupyter notebook works and I am not using `code-davinci-002` but when I run `main_batch.py` without the multi-processing, it loads BLIP and CLIP and then exits.

**Comment by surisdi** [comment]
Have you tried updating the `HiddenPrints`? Sometimes it hides error messages.

**Comment by surisdi** [comment]
Closing issue, feel free to re-open if there are any updates
