### ISSUE TITLE
Disk quota for running main_batch.py 

### ISSUE THREAD

**Issue by Anthony6197** [cvlab-columbia/viper#30]
Hi, 

  When I run the main_batch with `CONFIG_NAME=base_config python main_batch.py`, It downloads files that saturated my disk quota 20G (I am working on a remote cluster) and report disk quota exceed error and then exit. May I ask if that is what quota should I expect by running main_batch with base_configs (I only modify the directory of pre-trained model and data)? Here is a screen shot of the error:
<img width="1170" alt="Screenshot 2023-06-17 at 7 20 05 PM" src="https://github.com/cvlab-columbia/viper/assets/50277615/4ac3bf0e-a346-458d-ae49-a5bc23b6b67a">
<img width="771" alt="Screenshot 2023-06-17 at 7 20 27 PM" src="https://github.com/cvlab-columbia/viper/assets/50277615/51fbad42-ee9c-4362-bb18-4440272409fb">

**Comment by surisdi** [comment]
Hi, the vision models are very large. Just downloading the BLIP with flan-t5-xxl will take more space than the 20GB that you have available. It would be ideal to get a larger disk quota. Otherwise, you can try using smaller models (e.g. change the `blip_v2_model_type: blip2-flan-t5-xxl` configuration for another pre-trained BLIP one).

**Comment by surisdi** [comment]
Marking the stale issue as resolved. Feel free to reopen if there are any updates.
